import WorkIcon from "../../images/work.svg"

export const Work= {
    id:'work',
    topLine: 'Work Experiences',
    headLine: '3 Past Internships + 1 Part-time',
    company1: 'MFEC Public Company Limited',
    position1: 'Full Stack Developer Intern',
    date1: 'Date: December 2021 - February 2022',
    skills1: 'Express.js, React.js, Cypress.js, PostgreSQL, Docker',
    company2: 'Kasikorn Business-Technology Group',
    position2: 'Software Quality Management Intern',
    date2: 'Date: June 2022 - August 2022',
    skills2: 'Python, Robot',
    company3: 'Glasgow University Software Service (GUSS)',
    position3: 'Software Developer Part-time',
    date3: 'Date: November 2022 - June 2023',
    skills3: 'Django, JavaScript, Docker, PostgreSQL, HTML, CSS',
    company4: 'JPMorgan Chase & Co.',
    position4: 'Full Stack Developer Intern',
    date4: 'Date: June 2023 - August 2023',
    skills4: 'Spring Boot, TypeScript, Oracle SQL, React.js, CSS',
    buttonLabel: 'LinkedIn',
    to:{pathname:'https://www.linkedin.com/in/boondirekk/'},
    target: "_blank",
    imgStart: false,
    img: WorkIcon,
    alt: "Work Experiences",
}